.MODEL SMALL
.STACK 100
.DATA
STRING DB "ENTER STRING:","$"
STRING2 DB 13,10,"STRING OUTPUT IS: $"
ARR DB 50 DUP("$")
ENDS
.CODE
MAIN PROC
MOV AX,@DATA
MOV DS,AX
LEA DX,STRING
MOV AH,09H;STRING DISPLAY
INT 21H
MOV AH,10;STRING INPUT
LEA DX,ARR;OFFSET ADDRESS
MOV ARR,25 ;ARRAY SIZE<=50
INT 21H
LEA DX,STRING2
MOV AH,09H
INT 21H
LEA DX,ARR+2
MOV AH,09H
INT 21H
MOV AX,4C00H
INT 21H
MAIN ENDS
END MAIN