.MODEL SMALL
.STACK 100
.DATA
STR1 DB, "COMPUTER", "$" ;STRING DATA 
STR2 DB ? ;LOCATION TO BE TRANSFERED
ST1 DB, "ST1:$" ;DISPLAY ST1
ST2 DB, "ST2:$";DISPLAY ST2
LEN DB 0AH ;TO CALCULATE LEN TO THE STRING 
.CODE
MAIN PROC
MOV AX,@DATA
MOV ES,AX
LEA SI,STR1  ;LOCATION OF STR1
LEA DI,STR2  ;LOCATION OF STR2

L1:;DISPLAY ST1
LEA DX,ST1
MOV AH, 09H
INT 21H


L2:;DISPLAY CONTENT OF STR1
LEA DX,STR1
MOV AH,09H
INT 21H

L3:;DISPLAY ST2
LEA DX,ST2
MOV AH,09H
INT 21H

;TRANSFERING DATA
CLD;CLEAR DF FLAG
MOV CX,00H;CX SHOULD BE EMPTY 00
MOV CL,LEN
REP MOVSB 

;DISPLAY TRANSFER CONTENT
LEA DX, STR2
MOV AH,09H
INT 21H

MOV AH,04CH
INT 21H
MAIN ENDP
END MAIN

